### PR TITLE
Rebase git-solo, from git-intro

### PR DESCRIPTION
**Pull request by Sabryr**
This is to keep the history and contribution credits intact. 
 git tag -l
sabryrs-rebase-point-starting-of-solo

### CODE REVIEW

**Comment by wikfeldt** [comment]
sorry i don't follow, where's the history from git-intro?

**Comment by wikfeldt** [comment]
i thought we'd just do a PR from git-solo to git-intro

**Comment by Sabryr** [comment]
Probably a misunderstanding on my part. 
What I have done is to start git-solo from where git-intro ended. "git tag -l. The point git-solo start is tagged "git show sabryrs-rebase-point-starting-of-solo"

**Comment by Sabryr** [comment]
Sorry last commit might be misleading, as the history is not shared, I had to do a touch up so I can request the merge

**Comment by bast** [comment]
I am also confused. I also expected that we "replay" the git-solo changes on top of git-intro since we were interested in keeping the git-intro history.

**Comment by Sabryr** [comment]
"I am also confused. I also expected that we "replay" the git-solo changes on top of git-intr" is what I have done

**Comment by Sabryr** [comment]
This is not "replay the git-solo changes on top of git-intro"  . This is rebase  git-solo from git-intro.

**Comment by bast** [comment]
But this patch changes one single line (?) - in other words I don't get it :-)

**Comment by bast** [comment]
> i thought we'd just do a PR from git-solo to git-intro

yes, this is what I expected

**Comment by Sabryr** [comment]
If hard to understand then no point wasting time here, we should go for the other way of combining. For the sack of the argument, after playing git-solo from git-intro,  the tips of current git-solo and the new git-solo with the added history are the same. So to merge, a cosmetic commit needed

**Comment by bast** [comment]
Our goal was to keep the past history which was "lost" in git-solo and I don't see that part here.

**Comment by Sabryr** [comment]
Not to argue for this merge, but for the sack of understanding what I have done.
$ git checkout rebasing-from-git-intro
..
..
..
* c4b419c update index with new plan for lesson
* e8b0943 add config and index files
* 0888d83 use https with submodule
* 8aee34b add license
* 0beffff add jekyll-common submodule
* b3f22de (tag: sabryrs-rebase-point-starting-of-solo) initial commit
*   a48beec Merge pull request #144 from coderefinery/bash-prompt-tail
|\  
| * c0a730b Improve the bash prompt tails some
|/  
*   2e8f033 Merge pull request #141 from rkdarst/history-view-improvements
|\  
| * 093db21 Add code for fish shell (thanks Juho)
| * de1e69b guide: Update the history view commands to work in more cases
|/  
* 10f220b add quotes around alias
*   8f75b4b Merge pull request #139 from wikfeldt/thor/fix-img-guide
 ..
...
..
------------------------
The following is an example commit done to git-intro, but now in git-solo
 git show 093db21
commit 093db217b34d3119118a32d7265e2a24065a7eb8
Author: Richard Darst <rkd@zgib.net>
Date:   Wed Dec 12 19:38:17 2018 +0200

    Add code for fish shell (thanks Juho)

diff --git a/guide.md b/guide.md
index 60d421a..0d5f4b2 100644
--- a/guide.md
+++ b/guide.md
@@ -81,6 +81,8 @@ tail -n 0 -f demos.out | awk '{ if (match($0,/^[^$]+[$][^ ]* (.*)/,m)) print m[1
 tail -n 0 -f demos.out | awk '{ if (match($0,/^[^@]+@[^$]+[$][^ ]* (.*)/,m)) print m[1] }'
 # Prompt is $ ' alone on a line.
 tail -n 0 -f demos.out | awk '{ if (match($0,/^[$] (.*)/,m)) print m[1] }'
+# used for the fish shell (note: untested)
+tail -f -n 0 ~/fish_history | sed -u -e s'/- cmd:/ \>/'
 ```

**Comment by wikfeldt** [comment]
so all commits on git-solo are replayed on top of all commits on git-intro? if it works than all is good! it's just that one can't see anything in this PR

**Pull request merged**
