### PR TITLE
insert archeology episode after remotes intro

### PR DESCRIPTION
**Pull request by wikfeldt**
todo:
- replace git repo with something simple, or perhaps simply use guacamole recipe
- shorten significantly

### CODE REVIEW

**Comment by Sabryr** [comment]
Prefer is we can remove the guacamole recipe

**Comment by wikfeldt** [comment]
you mean replace the guacamole recipe for the entire lesson? that might be good to do later on, but the plan now is to take smaller steps and keep guacamole for the time being. so we need something to replace the git repo as an example since it's too large and complicated

**Comment by Sabryr** [comment]
What I mean is better not to use guacamole recipe as "Prefer if we can remove the guacamole recipe" as an alternative to the ".git" of Git.  A ground up repo as for the bisect lesson would be ideal. Anyway please do as best suits for the moment and can always improve later.

**Comment by wikfeldt** [comment]
i'm actually replacing the git repo now with word-count. This will hopefully be useful if/when we later switch to the word-count project in git-solo

**Comment by wikfeldt** [comment]
branch now ready for reviewing and merging. It's really difficult to cut away material since it's all very good, but hopefully it'll be easier to do later when we've taught this lesson once and seen how it works in practice

**Comment by bast** [comment]
So guacamole is gone? It was not clear to me from above comments.

**Comment by bast** [comment]
If yes, I am not too happy that we expose people to both Git and Python at the same time.

**Comment by wikfeldt** [comment]
no the guacamole discussion was whether to use guacamole repo instead of git repo for archeology episode (which it never was). instead i've used word-count, git repo is gone

**Comment by wikfeldt** [comment]
guacamole is still used everywhere up until the archeology episode

**Comment by bast** [comment]
Oh you meant the Git git repo. For the archaeology part I agree that it is good to not use the Git git repo.

**Comment by wikfeldt** [comment]
ok thanks for reviewing, i'll merge

**Pull request merged**
